pipeline {
    agent any

    triggers {
        pollSCM('*/3 * * * *')
    }

    stages {
        stage('Build') {
            steps {
                echo "Building ..."
                sh '''
                ls ./dockery/
                cd ./dockery/
                docker build -t ob_build:latest -f Dockerfile .
                docker run --name container_build ob_build:latest
                '''
            }
        }
        stage('Test') {
            steps {
                echo "Testing ..."
                sh '''
                ls ./dockery/
                cd ./dockery/
                docker build -t ob_test:latest -f DockerfileTest .
                docker run --name container_test ob_test:latest
                '''
            }
        }
        stage('logi') {
            steps {
                echo 'logi:'
                sh '''
                ls ./dockery/
                cd ./dockery/
                docker logs container_build > logi-build.txt
                docker logs container_test > logi-test.txt
                '''
            }
        }
    }
}