pipeline {
    agent any

    triggers {
        pollSCM('*/3 * * * *')
    }

    stages {
        stage('Build') {
            steps {
                echo "Build and test"
                sh '''
                cd ./pliki/dockery
                docker compose up --exit-code-from app
                '''
            }
        }
        stage('logi') {
            steps {
                echo 'logi:'
                sh '''
                cd ./pliki/dockery
                docker logs container_build > logi-build.txt
                docker logs container_test > logi-test.txt
                docker compose down
                '''
            }
        }
    }
}