pipeline {
    agent any

    triggers {
        pollSCM('*/3 * * * *')
    }

    stages {
        stage('Build') {
            steps {
                echo "Building ..."
                sh '''
                cd ./pliki/dockery
                docker build -t ob_build:latest -f Dockerfile .
                docker run --name container_build ob_build:latest && docker wait container_build && docker stop container_build
                '''
            }
        }
        stage('Test') {
            steps {
                echo "Testing ..."
                sh '''
                cd ./pliki/dockery
                docker build -t ob_test:latest -f DockerfileTest .
                docker run --name container_test ob_test:latest && docker wait container_test && docker stop container_test
                '''
            }
        }
        stage('logi') {
            steps {
                echo 'logi:'
                sh '''
                cd ./pliki/dockery
                docker logs container_build > logi-build.txt
                docker logs container_test > logi-test.txt
                '''
            }
        }
    }
}